supsm/mcpppp@mod:
  - source: MCPPPP-windows.cli.exe
    dest: src/main/resources/MCPPPP-windows.cli.exe
  - source: MCPPPP-linux
    dest: src/main/resources/MCPPPP-linux
  - source: MCPPPP-mac-cli
    dest: src/main/resources/MCPPPP-mac-cli