supsm/MCPPPP@mod:
  - source: gradle.properties
    dest: gradle.properties
  - source: mcpppp.dll
    dest: src/main/resources/mcpppp.dll
  - source: libmcpppp.so
    dest: src/main/resources/libmcpppp.so
  - source: libmcpppp.dylib
    dest: src/main/resources/libmcpppp.dylib