path_classifiers:
  library:
  - "lib/*"
  - "include/*"
  - "src/lodepng.cpp"
  - "src/microtar.cpp"
extraction:
  cpp:
    prepare:
      packages:
      - g++-9
    configure:
      command:
      - cmake -B build
    index:
      build_command:
      - cmake --build build --config release
