// generated by Fast Light User Interface Designer (fluid) version 1.0306

#ifndef mcpppp_h
#define mcpppp_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern void windowclosed(Fl_Double_Window*, void*);
#include <FL/Fl_Button.H>
extern void run(Fl_Button*, void*);
#include <FL/Fl_Browser.H>
#include <FL/Fl_Check_Button.H>
extern void conversion(Fl_Check_Button*, void*);
#include <FL/Fl_Scroll.H>
extern void browse(Fl_Button*, void*);
extern void reload(Fl_Button*, void*);
#include <FL/Fl_Input.H>
extern void editpath(Fl_Input*, void*);
extern void opensettings(Fl_Button*, void*);
extern void openhelp(Fl_Button*, void*);
#include <FL/Fl_Box.H>
extern void selectall(Fl_Check_Button*, void*);
#include <FL/Fl_Value_Slider.H>
extern void updateoutputlevel(Fl_Value_Slider*, void*);
extern void addrespath(Fl_Button*, void*);
extern void deleterespath(Fl_Button*, void*);
#include <FL/Fl_Group.H>
#include <FL/Fl_Counter.H>
extern void savesettings(Fl_Button*, void*);
#include <FL/Fl_Window.H>
#include <FL/Fl_Help_View.H>

class UI {
public:
  UI();
  Fl_Double_Window *window;
  Fl_Browser *output;
  Fl_Scroll *scroll;
  Fl_Input *path_input;
  Fl_Box *box1;
  Fl_Box *box2;
  Fl_Check_Button *allpacks;
  Fl_Value_Slider *outputlevelslider;
  Fl_Double_Window *edit_paths;
  Fl_Scroll *paths;
  Fl_Double_Window *settings;
  Fl_Button *autodeletetemptrue;
private:
  inline void cb_autodeletetemptrue_i(Fl_Button*, void*);
  static void cb_autodeletetemptrue(Fl_Button*, void*);
public:
  Fl_Button *autodeletetempfalse;
private:
  inline void cb_autodeletetempfalse_i(Fl_Button*, void*);
  static void cb_autodeletetempfalse(Fl_Button*, void*);
public:
  Fl_Input *log;
private:
  inline void cb_log_i(Fl_Input*, void*);
  static void cb_log(Fl_Input*, void*);
public:
  Fl_Button *timestamptrue;
private:
  inline void cb_timestamptrue_i(Fl_Button*, void*);
  static void cb_timestamptrue(Fl_Button*, void*);
public:
  Fl_Button *timestampfalse;
private:
  inline void cb_timestampfalse_i(Fl_Button*, void*);
  static void cb_timestampfalse(Fl_Button*, void*);
public:
  Fl_Counter *loglevel;
private:
  inline void cb_loglevel_i(Fl_Counter*, void*);
  static void cb_loglevel(Fl_Counter*, void*);
public:
  Fl_Button *autoreconverttrue;
private:
  inline void cb_autoreconverttrue_i(Fl_Button*, void*);
  static void cb_autoreconverttrue(Fl_Button*, void*);
public:
  Fl_Button *autoreconvertfalse;
private:
  inline void cb_autoreconvertfalse_i(Fl_Button*, void*);
  static void cb_autoreconvertfalse(Fl_Button*, void*);
public:
  Fl_Button *fsbtransparenttrue;
private:
  inline void cb_fsbtransparenttrue_i(Fl_Button*, void*);
  static void cb_fsbtransparenttrue(Fl_Button*, void*);
public:
  Fl_Button *fsbtransparentfalse;
private:
  inline void cb_fsbtransparentfalse_i(Fl_Button*, void*);
  static void cb_fsbtransparentfalse(Fl_Button*, void*);
public:
  Fl_Box *savewarning;
  Fl_Window *help;
  Fl_Window *path_warning;
private:
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  Fl_Check_Button *dontshowwarning;
  void show();
};
extern void settingchanged(Fl_Widget*, void*);
#endif
