// generated by Fast Light User Interface Designer (fluid) version 1.0306

#ifndef mcpppp_h
#define mcpppp_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
extern void run(Fl_Button*, void*);
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Check_Button.H>
extern void conversion(Fl_Check_Button*, void*);
#include <FL/Fl_Scroll.H>
extern void browse(Fl_Button*, void*);
extern void reload(Fl_Button*, void*);
#include <FL/Fl_Input.H>
extern void editpath(Fl_Input*, void*);
extern void addrespath(Fl_Button*, void*);
extern void deleterespath(Fl_Button*, void*);

class UI {
public:
  UI();
  Fl_Window *window;
  Fl_Text_Display *text_display;
  Fl_Scroll *scroll;
  Fl_Input *path_input;
  Fl_Window *edit_paths;
  Fl_Scroll *paths;
  void show();
};
#endif
