/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class supsm_mcpppp_jni */

#ifndef _Included_supsm_mcpppp_jni
#define _Included_supsm_mcpppp_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     supsm_mcpppp_jni
 * Method:    run
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_supsm_mcpppp_jni_run
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
