name: Compile Mac JNI Library

on:
  workflow_run:
    workflows:
    - Compile Linux JNI Library
    types:
    - requested
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: compile
      run: clang++ -shared -fPIC -std=c++20 -Ofast jni.cpp -o bin/libmcpppp.dylib -I$JAVA_HOME/include -I$JAVA_HOME/include/darwin
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'bin/libmcpppp.dylib'
        message: 'add mac jni library'
        push: true
