name: Sync Binaries

on:
  push:
    branches:
    - master
    paths:
    - 'MCPPPP-mac.tar.gz'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unzip
      run: tar -xvf MCPPPP-mac-cli.tar.gz
    - name: Sync
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        GH_PAT: ${{ secrets.GH_PAT }}