name: Sync

on:
  workflow_run:
    workflows:
    - Compile Mac
    types:
    - completed
    branches:
    - master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sync
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        GH_PAT: ${{ secrets.GH_PAT }}
        SKIP_PR: true